---
title: "ACP regional shapes"
author: "Matt Warham"
date: "7/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

connectivity_data <- read_sf("SubsidyAtlasACP/data/eez_results/ACP/eez_mapping_with_lines.shp")  
  
ACP_codes <- read_csv("SubsidyAtlasACP/data/ACP_eez_codes.csv")

africa_eez_choices <- ACP_codes$eez_id[ACP_codes$region == "Africa"]  
names(africa_eez_choices) <- ACP_codes$flag[ACP_codes$region == "Africa"]



ACP_codes_africa <- ACP_codes %>% 
  filter(region == "Africa") %>% 
  rename(iso3 = territory_iso3)

ACP_codes_caribbean <- ACP_codes %>% 
  filter(region == "Caribbean")

ACP_codes_pacific <- ACP_codes %>% 
  filter(region == "Pacific")

# EEZ map
EEZ_map <- read_sf(dsn = here::here("SubsidyAtlasACP", "data", "eez_v10_fao_combined_simple"), layer = "eez_v10_fao_combined_simple") %>% 
  st_transform(crs = 4326) 

EEZ_map_filterAfrica <- EEZ_map %>% 
  filter(ez_hs_c %in% ACP_codes_africa$territory_iso3) %>% 
  select(c("ez_hs_c"))

EEZ_map_filterCaribbean <- EEZ_map %>% 
  filter(ez_hs_c %in% ACP_codes_caribbean$territory_iso3) %>% 
  select(c("ez_hs_c"))

EEZ_map_filterPacific <- EEZ_map %>% 
  filter(ez_hs_c %in% ACP_codes_pacific$territory_iso3) %>% 
  select(c("ez_hs_c"))

# Country map
country_map <- read_sf(dsn = here::here("SubsidyAtlasACP", "data", "world_happy_180"), layer = "world_happy_180") %>%  
  st_transform(crs = 4326) 

country_map_filterAfrica <- country_map %>% 
  dplyr::filter(iso3 %in% ACP_codes$territory_iso3) %>% 
  filter(region == "Africa") %>% 
  select(c("iso3")) %>% 
  rename(ez_hs_c = iso3)

country_map_filterCaribbean <- country_map %>% 
  dplyr::filter(iso3 %in% ACP_codes$territory_iso3) %>% 
  filter(subregn == "Caribbean") %>% 
  select(c("iso3")) %>% 
  rename(ez_hs_c = iso3)

country_map_filterPacific <- country_map %>% 
  dplyr::filter(iso3 %in% ACP_codes$territory_iso3) %>% 
  filter(region == "Oceania") %>% 
  select(c("iso3")) %>% 
  rename(ez_hs_c = iso3)

### Bind Shapefiles


africa_bind <- rbind(EEZ_map_filterAfrica, country_map_filterAfrica)
ab <- st_union(africa_bind)  
  

caribbean_bind <- rbind(EEZ_map_filterCaribbean, country_map_filterCaribbean)
cb <- st_union(caribbean_bind) 
  

pacific_bind <- rbind(EEZ_map_filterPacific, country_map_filterPacific)
pb <- st_union(pacific_bind)  
  



ggplot()+
      geom_sf(data = EEZ_map %>% dplyr::filter(is.na(zone)), fill = NA, color = "grey60", size = 0.1)+ # world EEZs (transparent, light grey border lines)
      geom_sf(data = country_map, fill = "grey2", color = "grey40", size = 0.1)+ # world countries (dark grey, white border lines)
      #geom_sf(data = country_map_filterAfrica , fill = "slateblue", alpha = 0.5, color = NA, size = 0.1) + # highlighted flag states (magenta)
      #geom_sf(data = EEZ_map_filterAfrica , fill = "slateblue", color = "grey40", size = 0.1) + # highlighted EEZ (slateblue, grey border lines)
      geom_sf(data = country_map_filterPacific, fill = "slateblue", alpha = 1, color = NA, size = 0.1) +
      maptheme+
      coord_sf(xlim = c(-180,180), ylim = c(-90,90))+
      scale_x_continuous(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))

library(leaflet)
library(RColorBrewer)


# leaflet() %>% 
#       addProviderTiles("CartoDB.DarkMatterNoLabels") %>% 
#       addPolygons(data = ab, 
#                   fillColor = "slateblue",
#                   fillOpacity = 0.8,
#                   color= "white",
#                   weight = 0.3,
#                   highlight = highlightOptions(weight = 5,
#                                                color = "#666",
#                                                fillOpacity = 1,
#                                                bringToFront = TRUE),
#                   label = ("Africa")) %>%
#       addPolygons(data = cb, 
#                   fillColor = "seagreen",
#                   fillOpacity = 8,
#                   color= "white",
#                   weight = 0.3,
#                   highlight = highlightOptions(weight = 5,
#                                                color = "#666",
#                                                fillOpacity = 1,
#                                                bringToFront = TRUE),
#                   label = ("Caribbean")) %>% 
#     addPolygons(data = pb, 
#                   fillColor = "coral",
#                   fillOpacity = 8,
#                   color= "white",
#                   weight = 0.3,
#                   highlight = highlightOptions(weight = 5,
#                                                color = "#666",
#                                                fillOpacity = 1,
#                                                bringToFront = TRUE),
#                   label = ("Pacific")) #%>% 
  # observe({
  #       click <- input$livemap_shape_click
  #       if(is.null(click))
  #           return()
  # 
  #       ## use the click to access the zoom and set the view according to these
  #       ## the click$id is now returned with the 'name' of the state
  #       ## because we specified it in the LayerId argument
  #       idx <- which(mapStates$name == click$id)
  #       z <- mapStates$zoom[[idx]]
  # 
  #       leafletProxy("livemap") %>% 
  #           setView(lng = click$lng, lat = click$lat, zoom = z)
  #   })
  


land_eez_map <- read_sf(dsn = here::here("SubsidyAtlasACP", "data", "EEZ_land_union_v2_201410"), layer = "EEZ_land_v2_201410")

# leaflet() %>% 
#       addProviderTiles("CartoDB.DarkMatterNoLabels") %>% 
#       addPolygons(data = land_eez_map, 
#                   fillColor = "slateblue",
#                   fillOpacity = 0.8,
#                   color= "white",
#                   weight = 0.3,
#                   highlight = highlightOptions(weight = 5,
#                                                color = "#666",
#                                                fillOpacity = 1,
#                                                bringToFront = TRUE))
#                   


```



```{r}

country_map <- read_sf(dsn = "SubsidyAtlasACP/data/world_happy_180", layer="world_happy_180") %>%
  st_transform(crs = 4326)

country_map_filtered_africa_ZAF <- country_map %>% 
  dplyr::filter(iso3 %in% connectivity_data_filter_africa_ZAF$flag) %>% 
  rename(flag = iso3) %>% 
  arrange((cntry_l))

connectivity_data_filter_africa_ZAF <- connectivity_data %>% # load this in up above
      dplyr::filter(eez_cod == "8396") 



connectivity_data_filter_africa_ZAF4 <- connectivity_data_filter_africa_ZAF %>% 
  mutate(cntry_l = (country_map_filtered_africa_ZAF$cntry_l)) #%>% 
  #arrange(desc(flag))
      #st_join(select(country_map_filtered_africa_ZAF, cntry_l), by = unique("flag"))
    
    connectivity_data_filter_africa <- connectivity_data %>% # load this in up above
      dplyr::filter(eez_cod %in% ACP_codes_africa$eez_id) %>% 
      arrange(ez_tr_3) %>% 
      rename(territory_iso3 = ez_tr_3)
      #mutate(total_vessels = sum(vessels))
    
    total_stats_africa <- connectivity_data_filter_africa %>% 
        as.data.frame() %>% 
        select(c("eez_cod", "territory_iso3", "vessels", "capacty", "fshng_h", "fshn_KW")) %>% 
        group_by(eez_cod, territory_iso3) %>%
        summarize(vessels = sum(vessels, na.rm = T),
                  capacty = sum(capacty, na.rm = T),
                  fshng_h = sum(fshng_h, na.rm = T),
                  fshn_KW = sum(fshn_KW, na.rm = T)) %>% 
      arrange(territory_iso3)
    
    connectivity_data_filter_africa_test <- connectivity_data %>% # load this in up above
      dplyr::filter(eez_cod == "8396") 
    
    # Total stats by EEZ
    
    total_stats_africa_test <- connectivity_data_filter_africa_test %>% 
      as.data.frame() %>% 
      select(c("eez_cod", "ez_tr_3", "vessels", "capacty", "fshng_h", "fshn_KW")) %>% 
      group_by(eez_cod, ez_tr_3) %>%
      summarize(vessels = sum(vessels, na.rm = T),
                capacty = sum(capacty, na.rm = T),
                fshng_h = sum(fshng_h, na.rm = T),
                fshn_KW = sum(fshn_KW, na.rm = T)) #%>% 
      #arrange(ez_tr_3)
            
    
    
    country_map_filtered_africa11 <- country_map %>% 
      dplyr::filter(iso3 %in% connectivity_data_filter_africa11$flag) %>% 
      rename(flag = iso3) %>% 
      arrange(flag)
    
    country_final <- country_map_filtered_africa11 %>% 
      #mutate(cntry_l = (country_map_filtered_africa11$cntry_l)) %>% 
      mutate(vessels = (connectivity_data_filter_africa11$vessels)) %>% 
      mutate(capacty = (connectivity_data_filter_africa11$capacty)) %>% 
      mutate(fshn_KW = (connectivity_data_filter_africa11$fshn_KW)) %>% 
      mutate(fshng_h = (connectivity_data_filter_africa11$fshng_h))
      

connectivity_data_filter_africa_ZAF <- conn %>% left_join(select(TableB, id, x), by = "id")

connectivity_data_filter_suriname <- connectivity_data %>% # load this in up above
      dplyr::filter(eez_cod == 8461)

country_map_filtered_caribbean <- land_map %>% 
      dplyr::filter(iso3 %in% connectivity_data_filter_caribbean$flag) 

dw_effort_final_caribbean <- dw_effort_final %>% 
  filter(eez_code %in% ACP_codes_caribbean$eez_id) %>% 
  select(c("flag","flag_name","ssvid", "eez_code", "eez_territory_iso3","eez_territory_name", "fishing_hours_year_eez", "fishing_KWh")) %>% 
  group_by(flag, eez_code) #%>% 
  # summarize(fishing_hours = sum(fishing_hours_year_eez, na.rm = T),
  #           fishing_KWh = sum(fishing_KWh, na.rm = T),
  #           number_vessels = n_distinct(ssvid))

unique(dw_effort_final_caribbean$eez_territory_iso3)


dw_effort_final_africa <- dw_effort_final %>% 
  filter(eez_code %in% ACP_codes_africa$eez_id) %>% 
  select(c("flag","flag_name","ssvid", "eez_code", "eez_territory_iso3","eez_territory_name", "fishing_hours_year_eez", "fishing_KWh")) %>% 
  group_by(flag, eez_code, eez_territory_name) #%>% 
  # summarize(fishing_hours = sum(fishing_hours_year_eez, na.rm = T),
  #           fishing_KWh = sum(fishing_KWh, na.rm = T),
  #           number_vessels = n_distinct(ssvid))

unique(dw_effort_final_africa$eez_territory_iso3)

dw_effort_final_pacific <- dw_effort_final %>% 
  filter(eez_code %in% ACP_codes_pacific$eez_id) %>% 
  select(c("flag","flag_name","ssvid", "eez_code", "eez_territory_iso3","eez_territory_name", "fishing_hours_year_eez", "fishing_KWh")) %>% 
  group_by(flag, eez_code, eez_territory_name) #%>% 
  # summarize(fishing_hours = sum(fishing_hours_year_eez, na.rm = T),
  #           fishing_KWh = sum(fishing_KWh, na.rm = T),
  #           number_vessels = n_distinct(ssvid))

unique(dw_effort_final_pacific$eez_territory_iso3)
  
dw_effort_CPV <- dw_effort_final_africa %>% 
  filter (eez_code == "8362")

dw_effort_test <- dw_effort_final %>% 
  filter(eez_territory_iso3 == "LCA")

```

```{r}

## HEat maps

eez_effort <- read_csv(paste0(eez_results_app_dir, analysis_eezs[i], "_", analysis_eez_names[i], "_EEZ_effort_subs_by_flag.csv"), col_types = "iccnnnnn")

eez_effort_VUT <- read_csv("SubsidyAtlasACP/data/eez_results/ACP/8313_VUT_EEZ_effort_subs_by_flag.csv")



### Make Plots 
  # Get quantiles of data for scale limits
  eez_effort_aggregated_VUT <- eez_effort_VUT %>%
    group_by(year, eez_code, lon_cen, lat_cen) %>%
    summarize(fishing_hours = sum(fishing_hours, na.rm = T),
              fishing_KWh = sum(fishing_KWh, na.rm = T),
              subs = sum(subs, na.rm = T)) %>%
    mutate(subsidy_intensity = subs/fishing_KWh) %>% 
    rename(lng = lon_cen) %>% 
    rename(lat = lat_cen)
  
  # Quantiles
  intensity_quantile <- quantile(eez_effort_aggregated_VUT$subsidy_intensity, probs = c(0.01, 0.05, 0.95, 0.99), na.rm = T)
  scale_labels <- round(seq(round(intensity_quantile[1], 1), round(intensity_quantile[4], 1), length.out = 5), 1)
  
  # Set map limits for filtering global country map and eez map appropriately
  x_lim <- c(min(eez_effort_aggregated_VUT$lon_cen) - 0.5, max(eez_effort_aggregated_VUT$lon_cen) + 0.5)
  y_lim <- c(min(eez_effort_aggregated_VUT$lat_cen) - 0.5, max(eez_effort_aggregated_VUT$lat_cen) + 0.5)
  
  # Map of subsidy intensity
  eez_subsidy_plot_VUT <- ggplot()+
    geom_sf(data = EEZ_map %>% dplyr::filter(is.na(zone)), fill = NA, color = "grey60", size = 0.5)+ # world EEZs (transparent, light grey border lines)
    geom_sf(data = country_map, fill = "grey2", color = "grey40", size = 0.5)+ # world countries (dark grey, white border lines)
    geom_raster(data = eez_effort_aggregated_VUT, aes(x = lon_cen, y = lat_cen, fill = subsidy_intensity))+
    eezmaptheme +
    scale_fill_viridis_c(na.value = NA, name = "Subsidy intensity \n(2018 $USD/KWh)", 
                         limits=c(round(intensity_quantile[1],1)-round(intensity_quantile[1],1)*0.01, round(intensity_quantile[4], 1) + round(intensity_quantile[4], 1)*0.01), 
                         labels=scale_labels,
                         breaks=scale_labels,
                         oob=scales::squish)+
    labs(x = "", y = "")+
    coord_sf(xlim = x_lim, ylim = y_lim)+
    guides(fill = guide_colorbar(title.position = "bottom", title.hjust = 0.5, barwidth = 18))+
    scale_x_continuous(expand = c(0,0))+
    scale_y_continuous(expand = c(0,0))
  
eez_subsidy_plot_VUT
  
  ggsave(eez_subsidy_plot, filename = paste0(eez_figures_dir, analysis_eezs[i], "_", analysis_eez_names[i], "_EEZ_subsidy_map.png"), width = 10, units = "in")
  
  # Labels for the log scale 
  eez_effort_plot <- ggplot()+
    geom_sf(data = EEZ_map %>% dplyr::filter(is.na(zone)), fill = NA, color = "grey60", size = 0.5)+ # world EEZs (transparent, light grey border lines)
    geom_sf(data = country_map, fill = "grey2", color = "grey40", size = 0.5)+ # world countries (dark grey, white border lines)
    geom_raster(data = eez_effort_aggregated, aes(x = lon_cen, y = lat_cen, fill = fishing_KWh))+
    eezmaptheme +
    scale_fill_viridis_c(na.value = NA, option = "A", name = "Fishing effort \n(KWh)", trans = log10_trans(), labels = comma)+
    labs(x = "", y = "")+
    coord_sf(xlim = x_lim, ylim = y_lim) +
    guides(fill = guide_colorbar(title.position = "bottom", title.hjust = 0.5, barwidth = 18))+
    scale_x_continuous(expand = c(0,0))+
    scale_y_continuous(expand = c(0,0))
  
  ggsave(eez_effort_plot, filename = paste0(eez_figures_dir, analysis_eezs[i], "_", analysis_eez_names[i], "_EEZ_effort_map.png"), width = 10, units = "in")



```


```{r}

s = SpatialPixelsDataFrame(eez_effort_aggregated_VUT[,c('lon_cen', 'lat_cen')], data = eez_effort_aggregated_VUT)
crs(s) = sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# Quantiles
  intensity_quantile <- quantile(eez_effort_aggregated_VUT$subsidy_intensity, probs = c(0.01, 0.05, 0.95, 0.99), na.rm = T)
  scale_labels <- round(seq(round(intensity_quantile[1], 1), round(intensity_quantile[4], 1), length.out = 5), 1)
  
  # Set map limits for filtering global country map and eez map appropriately
  x_lim <- c(min(eez_effort_aggregated_VUT$lon_cen) - 0.5, max(eez_effort_aggregated_VUT$lon_cen) + 0.5)
  y_lim <- c(min(eez_effort_aggregated_VUT$lat_cen) - 0.5, max(eez_effort_aggregated_VUT$lat_cen) + 0.5)

val = as.numeric(c(eez_effort_aggregated_VUT$subsidy_intensity))  
pal = colorNumeric(c("yellow", "orange", "red"), intensity_quantile,
                na.color = "transparent")



r <- raster(s)

pal <- colorNumeric(
  palette = "YlGnBu",
  domain = eez_effort_aggregated_VUT$subsidy_intensity)

leaflet(eez_effort_aggregated_VUT) %>% 
  addProviderTiles("CartoDB.DarkMatterNoLabels") %>%
  # addHeatmap(eez_effort_aggregated_VUT, lng = ~lng, lat = ~lat, intensity = ~subsidy_intensity,
  #   layerId = NULL, group = NULL, minOpacity = 1, max = 1,
  #   radius = 10, blur = 0, gradient = NULL, cellSize = NULL) %>% 
  addHeatmap(lng = ~lng, lat = ~lat, intensity = ~subsidy_intensity, blur = 1, max = 10, radius = 10, cellSize = 1, gradient=  rev(RColorBrewer::brewer.pal(3,"YlGnBu")))
  #addCSVHeatmap(eez_effort_aggregated_VUT, csv, csvParserOptions())
  #addWebGLHeatmap(size=20, units = 'px')
      #addRasterImage(r, colors = pal, opacity = 0.8) %>% 
      #addLegend(pal = pal, values = val, title = "Subsidies")

#data = eez_effort_aggregated_VUT, aes(x = lon_cen, y = lat_cen, fill = subsidy_intensity
      
    

```

```{r}

eez_effort_africa <- read_csv("SubsidyAtlasACP/data/eez_results/ACP/8313_VUT_EEZ_effort_subs_by_flag.csv") %>% 
      as.data.frame()


    #Gemerate plot
    
     ### Make Plots 
     # Get quantiles of data for scale limits
     eez_effort_aggregated_africa <- eez_effort_africa %>%
       group_by(year, eez_code, lon_cen, lat_cen) %>%
       summarize(fishing_hours = sum(fishing_hours, na.rm = T),
                 fishing_KWh = sum(fishing_KWh, na.rm = T),
                 subs = sum(subs, na.rm = T)) %>%
       mutate(subsidy_intensity = subs/fishing_KWh)
     
     
     # # # Quantiles
     intensity_quantile <- quantile(eez_effort_aggregated_africa$subsidy_intensity, probs = c(0.01, 0.05, 0.95, 0.99), na.rm = T)
     scale_labels <- round(seq(round(intensity_quantile[1], 1), round(intensity_quantile[4], 1), length.out = 5), 1)
     
    # # # Set map limits for filtering global country map and eez map appropriately
     x_lim <- c(min(eez_effort_aggregated_africa$lon_cen) - 0.5, max(eez_effort_aggregated_africa$lon_cen) + 0.5)
     y_lim <- c(min(eez_effort_aggregated_africa$lat_cen) - 0.5, max(eez_effort_aggregated_africa$lat_cen) + 0.5)
     
    # Map of subsidy intensity
    Africa_eez_subsidy_plot <- ggplot()+
      geom_sf(data = EEZ_map %>% dplyr::filter(is.na(zone)), fill = NA, color = "grey60", size = 0.5)+ # world EEZs (transparent, light grey border lines)
      geom_sf(data = country_map, fill = "grey2", color = "grey40", size = 0.5)+ # world countries (dark grey, white border lines)
      geom_raster(data = eez_effort_aggregated_africa, aes(x = lon_cen, y = lat_cen, fill = subsidy_intensity))+
      eezmaptheme +
      scale_fill_viridis_c(na.value = NA, name = "Subsidy intensity \n(2018 $USD/KWh)", 
                           limits=c(round(intensity_quantile[1],1)-round(intensity_quantile[1],1)*0.01, round(intensity_quantile[4], 1) + round(intensity_quantile[4], 1)*0.01), 
                           labels=scale_labels,
                           breaks=scale_labels,
                           oob=scales::squish)+
      labs(x = "", y = "")+
      coord_sf(xlim = x_lim, ylim = y_lim)+
      guides(fill = guide_colorbar(title.position = "bottom", title.hjust = 0.5, barwidth = 18))+
      scale_x_continuous(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))
    
    plot(Africa_eez_subsidy_plot)

```

