---
title: "test script"
author: "Matthew Warham"
date: "6/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### Example of how to clip the -360 to 360 degree land/eez merged shapefile

library(sf)
library(mapview)
library(tidyverse)

# Load map
full_eez_map <- read_sf(dsn = here::here("SubsidyAtlasACP", "data", "shapefiles_edit", "test"), layer = "test") %>%
    st_transform(crs = 4326) 

# Filter full map by regional bounding boxes
pacific_map <- st_crop(full_eez_map, c(xmin=0, xmax=360, ymin=-90, ymax=90))
africa_map <- st_crop(full_eez_map, c(xmin=-180, xmax=180, ymin=-90, ymax=90))
caribbean_map <- st_crop(full_eez_map, c(xmin=-260, xmax=100, ymin=-90, ymax=90))

ggplot(caribbean_map)+
  geom_sf()

```

```{r}

ACP_codes <- read_csv("ACP_eez_codes.csv")

africa_eezs <- ACP_codes %>% 
    dplyr::filter(region == "Africa") %>% 
    select(eez_id)

country_map <- read_sf(dsn = here::here("SubsidyAtlasACP", "data", "world_happy_180"), layer = "world_happy_180") %>%  
  st_transform(crs = 4326)

EEZ_map <- read_sf(dsn = here::here("SubsidyAtlasACP", "data", "eez_v10_fao_combined_simple"), layer = "eez_v10_fao_combined_simple") %>% 
  st_transform(crs = 4326) 

eez_fao <- read_sf(dsn = "./data/eez_v10_fao_combined_simple", layer="eez_v10_fao_combined_simple") %>%
  dplyr::filter(is.na(zone))

ACP_codes %>% 
    select(eez_id)

ACP_codes <- eez_fao %>% 
       dplyr::filter(mrgid %in% ACP_codes$eez_id)

EEZ_map <- read_sf(dsn = here::here("SubsidyAtlasACP", "data", "eez_v10_fao_combined_simple"), layer = "eez_v10_fao_combined_simple") %>% 
  st_transform(crs = 4326) 

conectivity_data_new <- read_sf("./data/ACP_eez_results/ACP_eez_mapping_wlines.shp") %>% 
  rename(eez_territory_iso3 = ez_tr_3)

connectivity_data <- read_sf("./data/ACP_eez_results/ACP_eez_mapping_wlines.shp") %>% 
  rename(eez_territory_iso3 = ez_tr_3)
  

connectivity_data %>% # load this in up above
       dplyr::filter(eez_code == input$country_for_profile)

test_data2 <- connectivity_data %>% # load this in up above
      dplyr::filter(eez_code == input$country_for_profile)

connectivity_data_AGO <- connectivity_data %>% 
  dplyr::filter(eez_territory_iso3 == "AGO")

country_map2 <- country_map %>% 
  dplyr::filter(iso3 %in% connectivity_data_AGO$flag)

country_map4 <- country_map %>% 
  dplyr::filter(iso3 %in% connectivity_data$flag)

connectivity_data_VUT <- connectivity_data %>% 
      dplyr::filter(eez_territory_iso3 == "VUT")

ggplot()+
      geom_sf(data = EEZ_map %>% dplyr::filter(is.na(zone)), fill = NA, color = "grey60", size = 0.1)+ # world EEZs (transparent, light grey border lines)
      geom_sf(data = country_map, fill = "grey2", color = "grey40", size = 0.1)+ # world countries (dark grey, white border lines)
      geom_sf(data = country_map %>% dplyr::filter(iso3 %in% connectivity_data_BRB$flag && eez_connectivity_BRB$eez_territory_iso3 == "BRB"), fill = "darkmagenta", alpha = 0.5, color = NA, size = 0.1) + # highlighted flag states (magenta)
      geom_sf(data = EEZ_map %>% dplyr::filter(ez_hs_c == "BRB"), fill = "slateblue", color = "grey40", size = 0.1) + # highlighted EEZ (slateblue, grey border lines)
      geom_sf(data = connectivity_data_BRB, col = "darkgoldenrod", size = 0.25) +
      maptheme+
      coord_sf(xlim = c(-180,180), ylim = c(-90,90))+
      scale_x_continuous(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))

connectivity_data_filter <- connectivity_data %>% # load this in up above
       dplyr::filter(eez_territory_iso3 == "VUT")

ACP_eez_dat_VUT <- connectivity_data %>%
      dplyr::filter(eez_code == "8313")

eez_fao <- read_sf(dsn = "./data/eez_v10_fao_combined_simple", layer="eez_v10_fao_combined_simple") %>%
  dplyr::filter(is.na(zone))

ACP_codes <- eez_fao %>% 
      dplyr::filter(mrgid %in% ACP_codes$eez_id)


    
ACP_codes_filtered <- ACP_codes %>% 
      dplyr::filter(eez_territory_iso3 == "VUT")

ACP_codes_filtered <- connectivity_data %>% # load this in up above
      dplyr::filter(eez_territory_iso3 == "VUT")


```

