---
title: "Random Code MW"
author: "Matthew Warham"
date: "May 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r CHINA}

CHN <- vessel_tidy %>% 
  filter(flag == "CHN") 

length(unique(CHN$ssvid)) #6255 unique vessels

unique(CHN$vessel_class)

#View(CHN)

## Number of EEZ's that China fished in in 2018 (top 20)
CHN_eez <- vessel_tidy %>% 
  filter(flag == "CHN") %>% 
  group_by(flag, eez_iso3) %>% 
  summarize(effort_per_eez = sum(fishing_hours_year_eez_fao, na.rm = TRUE)) #%>% 
  #top_n(20)

#View(CHN_eez)

```

```{r Taiwan}

TWN <- vessel_tidy %>% 
  filter(flag == "TWN") 

length(unique(TWN$ssvid)) #6255 unique vessels

unique(TWN$vessel_class)



TWN <- vessel_tidy %>% 
  filter(flag == "TWN") 

length(unique(TWN$ssvid)) #6255 unique vessels

unique(TWN$vessel_class)

#View(TWN)

write_csv(TWN, "TWN.csv")

```


```{r}

KIR <- vessel_tidy %>% 
  filter(eez_iso3 == "KIR")

length(unique(KIR$ssvid))
sum(KIR$fishing_hours_year_eez_fao)
mean(KIR$fishing_hours_year_eez_fao)
sum(KIR$kwhr_in_eez)
mean(KIR$kwhr_in_eez)

#View(KIR)

NAM <- vessel_tidy %>% 
  filter(eez_iso3 == "NAM")

length(unique(NAM$ssvid))
sum(NAM$fishing_hours_year_eez_fao)
mean(NAM$fishing_hours_year_eez_fao)
sum(NAM$kwhr_in_eez)
mean(NAM$kwhr_in_eez)

#View(NAM)

NZL <- vessel_tidy %>% 
  filter(eez_iso3 == "NZL")

length(unique(NZL$ssvid))
sum(NZL$fishing_hours_year_eez_fao)
mean(NZL$fishing_hours_year_eez_fao)
sum(NZL$kwhr_in_eez)
mean(NZL$kwhr_in_eez)


#View(NZL)

KOR <- vessel_tidy %>% 
  filter(eez_iso3 == "KOR")

length(unique(KOR$ssvid))
sum(KOR$fishing_hours_year_eez_fao)
mean(KOR$fishing_hours_year_eez_fao)
sum(KOR$kwhr_in_eez)
mean(KOR$kwhr_in_eez)

CHN <- vessel_tidy %>% 
  filter(eez_iso3 == "CHN")

length(unique(CHN$ssvid))
sum(CHN$fishing_hours_year_eez_fao)
mean(CHN$fishing_hours_year_eez_fao)
sum(CHN$kwhr_in_eez)
mean(CHN$kwhr_in_eez)

write_csv(KIR,"KIR.csv")
write_csv(NAM,"NAM.csv")
write_csv(NZL, "NZL.csv")
write_csv(KOR, "KOR.csv")
write_csv(CHN, "CHN.csv")
write_csv(EEZ,"EEZ.csv")


#test_eezs <- read_csv("~/GitHub/subsidy-atlas/MW Results/test_eezs.csv")
#View(test_eezs)



```

```{r Random Map Code}



#ggplot(EEZ_pacific)+
  #geom_sf(aes(fill = iso_tr1),
         # color = "NA",  # gets rid of lines
          #show.legend = FALSE)+
  #scale_fill_manual(values = my_colors)+ # change color scheme to the one we created earlier
  #geom_sf(data = ca_counties,
          #fill = "NA",
          #color = "black", #color of line
          #size = 0.1)+
  #geom_point(data = ca_dams, # add dams layer
            # aes(x = Longitude, y = Latitude),
             #size = 1,
             #color = "gray10",
             #alpha = 0.5)+
  #theme_minimal()+
  #coord_sf(datum = NA) #remove coordinate axis

#CHN <- EEZ_pacific %>% 
  #filter(ez_hs_c == "CHN")

#USA <- EEZ %>% 
  #filter(ez_hs_c == "USA" | ez_hs_c == "ARG" | ez_hs_c==)


## Mexico Example
#MEX <- EEZ %>% 
 # filter(ez_hs_c == "MEX" | ez_hs_c == "CAN" |ez_hs_c == "CHN" |ez_hs_c == "GBR" | ez_hs_c == "ISL" | ez_hs_c == "LTU" | ez_hs_c == "USA" | ez_hs_c == "VEN")

#ggplot(MEX)+
  #geom_sf(data = EEZ, fill = "lightskyblue2")+
  #geom_sf(aes(fill = ez_hs_c), color = "NA")+
  #scale_fill_manual(values = c("blue", "blue", "blue", "blue", "blue", "red", "blue", "blue"))

#plot(MEX)

## ARG example

## Mac load
#ARG <- read_csv("~/Documents/GitHub/subsidy-atlas/MW Results/ARG.csv")
#View(ARG)

## PC load
#ARG <- read_csv("~/GitHub/subsidy-atlas/MW Results/ARG.csv")
#View(ARG)

#ARG_1 <- EEZ %>% 
  #filter(ez_hs_c == ARG$EEZs)

#View(ARG_1)

#ggplot(ARG_1)+
  #geom_sf(data = EEZ, fill = "lightskyblue2")+
  #geom_sf(aes(fill = ez_hs_c), color = "NA")

##AUS Example
##Mac load

#AUS <- read_csv("~/Documents/GitHub/subsidy-atlas/MW Results/AUS.csv")
#View(AUS)

##PC Load
#AUS <- read_csv("~/GitHub/subsidy-atlas/MW Results/AUS.csv")
#View(AUS)

#AUS_1 <- EEZ %>% 
 # filter(ez_hs_c == AUS$EEZs)

#View(AUS_1)

#ggplot(ARG_1)+
  #geom_sf(data = EEZ, fill = "lightskyblue2")+
  #geom_sf(aes(fill = ez_hs_c), color = "NA")

## Sample Code


##Maps


```




